CREATE DATABASE IF NOT EXISTS Producao;
USE Producao;

CREATE TABLE IF NOT EXISTS Fabricante (
    FabricanteID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Localizacao VARCHAR(255) NOT NULL,
    Descricao VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Categoria (
    CategoriaID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Status VARCHAR(50) NOT NULL,
    Descricao VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Produto (
    ProdutoID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Preco DECIMAL(10, 2) UNSIGNED NOT NULL,
    FabricanteID INT UNSIGNED NOT NULL,
    CategoriaID INT UNSIGNED NOT NULL,
    FOREIGN KEY (FabricanteID) REFERENCES Fabricante(FabricanteID) ON DELETE CASCADE,
    FOREIGN KEY (CategoriaID) REFERENCES Categoria(CategoriaID) ON DELETE CASCADE
);